phraseapp:
  access_token: ea94fb98f79c3b289eb011875aae577fb5346f34cecd7851ad5200476d17ad6a
  project_id: 4b4ed4b0323ba298c796154b07716faf
  push:
    sources:
    - file: "<locale_name>.json"
      params:
        file_format: json
  pull:
    targets:
    - file: "<locale_name>.json"
      params:
        update_translations: true
        file_format: json
